version: '3.6'
services:

  # PostgreSQL
  postgres:
    container_name: hermes-postgres
    build: ./postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_URL: postgres://admin:password@localhost:5432/hermes-cs
      POSTGRES_DB: hermes-cs
      POSTGRES_HOST: postgres
    ports:
      - "5432:5432"

  # Redis
  redis:
    container_name: hermes-redis
    image: redis
    ports:
      - "6379:6379"

  # Backend
  hermes-cs-api:
    container_name: hermes-backend
    build: ./
    volumes:
      - ./:/usr/src/hermes-cs-api
    command: npm start
    working_dir: /usr/src/hermes-cs-api
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://admin:password@postgres:5432/hermes-cs
      REDIS_URL: redis://redis:6379
      FRONTEND_URL: http://localhost:3001
      MAIL_USER: hermescs.help@gmail.com
      MAIL_PASS: sonjag6200@
    links:
      - postgres
      - redis
